#!/usr/bin/env python3
"""Compare HP1 and HP2 builds of KnowWonder's DLLs, and what that means for the functions Flipendo has ported.

Input: fingerprints made with tools/ida_fingerprint.py inside IDA, one per game and DLL:
    ../ida/fingerprints/hp1_<Dll>.json, ../ida/fingerprints/hp2_<Dll>.json   (Dll = Engine, Core, Fire, ...)
and the "// IDA <Dll>.dll: <decorated name> [...]" tags in kw/, hp1/ and hp2/.

Output: docs/re/hp2_compare.md (or the path given) with
  - per DLL: exports identical in both games, changed, only in HP1, only in HP2 (new in HP2);
  - every ported function (IDA tag): identical / changed (size HP1 -> HP2) / missing in HP2.
"identical" means the same normalized code (ida_fingerprint.py): the port should carry over unchanged. "offsets only"
means the same instructions with different struct offsets or constants (fields added to a class in HP2): ports that
look fields up by name carry over too. "changed" means different logic: compare with the HP2 code before reusing.

Usage: python tools/hp2_compare.py [out.md]
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FP_DIR = os.path.join(ROOT, "..", "ida", "fingerprints")
TAG = re.compile(r"//\s*IDA\s+(\w+)\.dll:\s*(\?\S+)")


def load(game, dll):
    path = os.path.join(FP_DIR, "%s_%s.json" % (game, dll))
    return json.load(open(path)) if os.path.exists(path) else None


def ported_tags():
    tags = {}
    for path in [p for d in ("kw", "hp1", "hp2") for p in glob.glob(os.path.join(ROOT, d, "**", "*.*"), recursive=True)]:
        if not path.endswith((".cpp", ".h")):
            continue
        for n, line in enumerate(open(path, encoding="utf-8", errors="replace"), 1):
            m = TAG.search(line)
            if m:
                name = m.group(2).rstrip(",;")
                tags.setdefault((m.group(1), name), "%s:%d" % (os.path.relpath(path, ROOT).replace("\\", "/"), n))
    return tags


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "docs", "re", "hp2_compare.md")
    dlls = sorted({os.path.basename(p)[4:-5] for p in glob.glob(os.path.join(FP_DIR, "hp1_*.json"))})
    lines = ["# HP1 vs HP2 engine code", "",
             "Generated by `tools/hp2_compare.py` from IDA fingerprints (`tools/ida_fingerprint.py`) of HP1 retail 1.0 and",
             "HP2 retail 1.0. *Identical* = same normalized code (relocations aside), so a port carries over as is.", "",
             "| DLL | exports HP1 | HP2 | identical | offsets only | changed | only HP1 | only HP2 |", "|---|---|---|---|---|---|---|---|"]
    fps = {}
    summary = []
    for dll in dlls:
        a, b = load("hp1", dll), load("hp2", dll)
        if a is None or b is None:
            continue
        fps[dll] = (a, b)
        both = set(a) & set(b)
        same = sum(1 for k in both if a[k]["hash"] == b[k]["hash"])
        offs = sum(1 for k in both if a[k]["hash"] != b[k]["hash"] and a[k]["shape"] == b[k]["shape"])
        pct = lambda n: "%d (%d%%)" % (n, 100 * n // max(len(both), 1))
        lines.append("| %s | %d | %d | %s | %s | %s | %d | %d |" % (
            dll, len(a), len(b), pct(same), pct(offs), pct(len(both) - same - offs), len(set(a) - set(b)), len(set(b) - set(a))))
        summary.append(lines[-1])

    tags = ported_tags()
    rows = {"identical": [], "offsets only": [], "changed": [], "missing in HP2": [], "HP2 only": [], "no fingerprint": []}
    for (dll, name), where in sorted(tags.items()):
        if dll not in fps:
            rows["no fingerprint"].append((dll, name, where, ""))
            continue
        a, b = fps[dll]
        if name not in a and name in b:
            rows["HP2 only"].append((dll, name, where, "HP2 %s" % b[name]["body"]))
        elif name not in a:
            rows["no fingerprint"].append((dll, name, where, "not in HP1 exports"))
        elif name not in b:
            rows["missing in HP2"].append((dll, name, where, ""))
        elif a[name]["hash"] == b[name]["hash"]:
            rows["identical"].append((dll, name, where, ""))
        elif a[name]["shape"] == b[name]["shape"]:
            rows["offsets only"].append((dll, name, where, "HP2 %s" % b[name]["body"]))
        else:
            rows["changed"].append((dll, name, where, "%d -> %d bytes, HP2 %s" % (a[name]["size"], b[name]["size"], b[name]["body"])))

    lines += ["", "## Ported functions (`// IDA` tags in kw/, hp1/ and hp2/)", "",
              "%d tagged exports: %s." % (len(tags), ", ".join("%d %s" % (len(v), k) for k, v in rows.items() if v))]
    for kind in ("changed", "missing in HP2", "HP2 only", "no fingerprint", "offsets only", "identical"):
        if not rows[kind]:
            continue
        lines += ["", "### %s (%d)" % (kind[0].upper() + kind[1:], len(rows[kind])), "", "| DLL | function | port | note |", "|---|---|---|---|"]
        for dll, name, where, note in rows[kind]:
            lines.append("| %s | `%s` | `%s` | %s |" % (dll, name, where, note))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("\n".join(summary))
    print(next(l for l in lines if "tagged exports" in l))
    print("->", out)


if __name__ == "__main__":
    main()
